CREATE SEQUENCE PUBLIC.SEQ_SUBTASK;

CREATE TABLE PUBLIC.SUBTASK(
    SUBTASKID NUMERIC(20),
    TASKID NUMERIC(20),
    DESCRIPTION VARCHAR(50),
    STATUS VARCHAR(10),
    CONSTRAINT PK_SUBTASK PRIMARY KEY (SUBTASKID),
    CONSTRAINT FK_TASK FOREIGN KEY (TASKID) REFERENCES PUBLIC.TASK (TASKID)
);