CREATE SEQUENCE PUBLIC.SEQ_TASK;

CREATE TABLE PUBLIC.TASK(
    TASKID NUMERIC(20),
    BOARDID NUMERIC(20),
    TITLE VARCHAR(50),
    DESCRIPTION VARCHAR(300),
    STATUS VARCHAR(10),
    CONSTRAINT PK_TASK PRIMARY KEY (TASKID),
    CONSTRAINT FK_BOARD FOREIGN KEY (BOARDID) REFERENCES PUBLIC.BOARD (BOARDID)
);